global class CLS_PortalAPIConstants{

    global Final Static String UNIQUE_IDENTIFIER = 'token'; 
    public Final Static String ERROR_MESSAGE_PARAM_NOT_FOUND = 'Param not found';
    public Final Static String ERROR_MESSAGE_SOMETHING_WENT_WRONG = 'Something went wrong.'; 
    public Final Static String OPEN_APPLICATION_STATUS;
    public final Static String KEY_RESPONSE;
    public final Static String EMAIL;
    public final Static String FIRST_NAME;
    public final Static String LAST_NAME  = 'LastName';
    public final Static String LOAN_AMOUNT = 'LoanAmount';
    public final Static String NET_PROCEEDS;
    public final Static String APPLICATION = 'application';
    public final Static String PROPERTY = 'property';
    public final Static String PORTALSTAGE = 'PortalStage';
   public final static String DOCUSIGN_45O6T_URL = 'DocusignURL' ;
    public final static String DOCUSIGN_LOANDOC_URL = 'DocusignURL' ;
    
}